export default {
  SOCKET_IO_CONNECTING: 'SOCKET_IO_CONNECTING',
  SOCKET_IO_CONNECT: 'SOCKET_IO_CONNECT',
  SOCKET_IO_CONNECTED: 'SOCKET_IO_CONNECTED',
  SOCKET_IO_DISCONNECT: 'SOCKET_IO_DISCONNECT',
  SOCKET_IO_DISCONNECTED: 'SOCKET_IO_DISCONNECTED',
  SOCKET_IO_EMIT: 'SOCKET_IO_EMIT',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  WITHDRAW_FROM_ACCOUNT: 'WITHDRAW_FROM_ACCOUNT',
  DEPOSIT_INTO_ACCOUNT: 'DEPOSIT_INTO_ACCOUNT'
};